'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuthStore } from '@/lib/store';
import { useTheme } from '@/lib/ThemeContext';
import { classesApi, studentsApi, attendanceApi, paymentsApi } from '@/lib/api';
import toast from 'react-hot-toast';
import type { Class, Student, Attendance, Payment, Teacher } from '@/lib/types';

export default function TeacherDashboardPage() {
  const router = useRouter();
  const { user, userType, isAuthenticated, logout } = useAuthStore();
  const { theme, toggleTheme } = useTheme();
  const [classes, setClasses] = useState<Class[]>([]);
  const [students, setStudents] = useState<Student[]>([]);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [selectedClass, setSelectedClass] = useState<Class | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'overview' | 'classes' | 'students' | 'attendance' | 'payments' | 'records' | 'reports'>('overview');
  const [attendanceDate, setAttendanceDate] = useState(new Date().toISOString().split('T')[0]);
  const [attendanceRecords, setAttendanceRecords] = useState<Record<string, 'present' | 'absent' | 'late'>>({});
  const [showAddStudentModal, setShowAddStudentModal] = useState(false);
  const [showAddClassModal, setShowAddClassModal] = useState(false);
  const [autoGeneratedId, setAutoGeneratedId] = useState('');
  const [newStudent, setNewStudent] = useState({
    name: '',
    email: '',
    classId: '',
  });
  const [newClass, setNewClass] = useState({
    name: '',
  });

  // Stats for overview cards
  const [stats, setStats] = useState({
    totalStudents: 0,
    todayAttendancePercentage: 0,
    totalClasses: 0,
    paymentStatusPercentage: 0,
  });

  const teacher = user as Teacher;
  const teacherId = teacher?.teacherId;

  useEffect(() => {
    if (!isAuthenticated || userType !== 'teacher') {
      router.push('/login');
      return;
    }
    loadData();
  }, [isAuthenticated, userType, router]);

  useEffect(() => {
    // Generate student ID when modal opens
    if (showAddStudentModal) {
      const timestamp = Date.now();
      const random = Math.floor(Math.random() * 1000);
      setAutoGeneratedId(`STU-${timestamp}-${random}`);
    }
  }, [showAddStudentModal]);

  const loadData = async () => {
    if (!teacherId) return;
    
    setIsLoading(true);
    try {
      const [classesRes, studentsRes] = await Promise.all([
        classesApi.getAll(teacherId),
        studentsApi.getAll(teacherId),
      ]);

      setClasses(classesRes.data);
      setStudents(studentsRes.data);
      
      // Calculate stats
      const totalStudents = studentsRes.data.length;
      const totalClasses = classesRes.data.length;
      
      // Mock attendance and payment percentages (you can fetch real data)
      const todayAttendancePercentage = totalStudents > 0 ? 85 : 0;
      const paymentStatusPercentage = totalStudents > 0 ? 75 : 0;

      setStats({
        totalStudents,
        todayAttendancePercentage,
        totalClasses,
        paymentStatusPercentage,
      });
      
      if (classesRes.data.length > 0 && !selectedClass) {
        setSelectedClass(classesRes.data[0]);
      }
    } catch (error) {
      console.error('Error loading data:', error);
      toast.error('Failed to load data');
    } finally {
      setIsLoading(false);
    }
  };

  const handleCreateClass = async () => {
    if (!newClass.name) {
      toast.error('Please enter a class name');
      return;
    }

    try {
      await classesApi.create({
        name: newClass.name,
        teacherId: teacher._id,
      });
      toast.success('Class created successfully');
      setShowAddClassModal(false);
      setNewClass({ name: '' });
      loadData();
    } catch (error: any) {
      console.error('Error creating class:', error);
      toast.error(error.response?.data?.error || 'Failed to create class');
    }
  };

  const handleCreateStudent = async () => {
    if (!newStudent.name || !newStudent.classId) {
      toast.error('Please fill in all required fields');
      return;
    }

    try {
      await studentsApi.create({
        ...newStudent,
        studentId: autoGeneratedId,
      });
      toast.success('Student added successfully');
      setShowAddStudentModal(false);
      setNewStudent({ name: '', email: '', classId: '' });
      setAutoGeneratedId('');
      loadData();
    } catch (error: any) {
      console.error('Error creating student:', error);
      toast.error(error.response?.data?.error || 'Failed to add student');
    }
  };

  const handleMarkAttendance = async () => {
    if (!selectedClass) {
      toast.error('Please select a class');
      return;
    }

    const classStudents = students.filter(s => s.classId === selectedClass._id);
    const recordsToSave = classStudents
      .filter(s => attendanceRecords[s._id])
      .map(s => ({
        studentId: s._id,
        date: new Date(attendanceDate).toISOString(),
        status: attendanceRecords[s._id],
        session: 'daily',
        month: new Date(attendanceDate).getMonth() + 1,
        year: new Date(attendanceDate).getFullYear(),
      }));

    if (recordsToSave.length === 0) {
      toast.error('Please mark attendance for at least one student');
      return;
    }

    try {
      await attendanceApi.bulkCreate(recordsToSave);
      toast.success('Attendance marked successfully');
      setAttendanceRecords({});
      loadData();
    } catch (error: any) {
      console.error('Error marking attendance:', error);
      toast.error(error.response?.data?.error || 'Failed to mark attendance');
    }
  };

  const handleLogout = () => {
    logout();
    router.push('/login');
  };

  const getClassStudents = (classId: string) => {
    return students.filter(s => s.classId === classId);
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ backgroundColor: 'var(--background)' }}>
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600 mx-auto mb-4"></div>
          <p style={{ color: 'var(--foreground)' }}>Loading dashboard...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen" style={{ backgroundColor: 'var(--background)' }}>
      {/* Header */}
      <header className="shadow-sm" style={{ backgroundColor: 'var(--card-bg)', borderBottom: '1px solid var(--border-color)' }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <div className="w-10 h-10 bg-indigo-100 rounded-lg flex items-center justify-center">
                <svg className="w-6 h-6 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                </svg>
              </div>
              <div>
                <h1 className="text-xl font-bold" style={{ color: 'var(--foreground)' }}>Teacher Dashboard</h1>
                <p className="text-sm" style={{ color: 'var(--foreground)', opacity: 0.7 }}>Welcome, {teacher?.name}</p>
              </div>
            </div>
            <div className="flex items-center space-x-3">
              <button
                onClick={toggleTheme}
                className="p-2 rounded-lg hover:bg-gray-100 transition"
                style={{ color: 'var(--foreground)' }}
                title="Toggle theme"
              >
                {theme === 'dark' ? '🌞' : '🌙'}
              </button>
              <button
                onClick={handleLogout}
                className="px-4 py-2 text-sm font-medium rounded-lg transition border"
                style={{ 
                  color: 'var(--foreground)',
                  backgroundColor: 'var(--card-bg)',
                  borderColor: 'var(--border-color)'
                }}
              >
                Logout
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Tabs */}
      <div style={{ backgroundColor: 'var(--card-bg)', borderBottom: '1px solid var(--border-color)' }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <nav className="flex space-x-8" aria-label="Tabs">
            {[
              { id: 'overview', name: 'Overview', icon: '📊' },
              { id: 'classes', name: 'My Classes', icon: '🏫' },
              { id: 'students', name: 'Students', icon: '🎓' },
              { id: 'attendance', name: 'Mark Attendance', icon: '✓' },
              { id: 'payments', name: 'Payments', icon: '💳' },
              { id: 'records', name: 'View Records', icon: '📋' },
              { id: 'reports', name: 'Reports', icon: '📈' },
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`py-4 px-1 border-b-2 font-medium text-sm transition cursor-pointer ${
                  activeTab === tab.id
                    ? 'border-indigo-500 text-indigo-600'
                    : 'border-transparent hover:border-gray-300'
                }`}
                style={{ color: activeTab === tab.id ? undefined : 'var(--foreground)' }}
              >
                <span className="mr-2">{tab.icon}</span>
                {tab.name}
              </button>
            ))}
          </nav>
        </div>
      </div>

      {/* Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Overview Tab */}
        {activeTab === 'overview' && (
          <div className="space-y-6">
            {/* Stats Grid - Matching Mobile App */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              <div className="rounded-xl shadow-sm p-6 card" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)', border: '1px solid' }}>
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium" style={{ color: 'var(--foreground)', opacity: 0.7 }}>Total Students</p>
                    <p className="text-3xl font-bold mt-2" style={{ color: 'var(--foreground)' }}>{stats.totalStudents}</p>
                  </div>
                  <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center">
                    <svg className="w-6 h-6 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
                    </svg>
                  </div>
                </div>
              </div>

              <div className="rounded-xl shadow-sm p-6 card" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)', border: '1px solid' }}>
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium" style={{ color: 'var(--foreground)', opacity: 0.7 }}>Today's Attendance</p>
                    <p className="text-3xl font-bold mt-2" style={{ color: 'var(--foreground)' }}>{stats.todayAttendancePercentage}%</p>
                  </div>
                  <div className="w-12 h-12 bg-teal-100 rounded-lg flex items-center justify-center">
                    <svg className="w-6 h-6 text-teal-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </div>
                </div>
              </div>

              <div className="rounded-xl shadow-sm p-6 card" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)', border: '1px solid' }}>
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium" style={{ color: 'var(--foreground)', opacity: 0.7 }}>Total Classes</p>
                    <p className="text-3xl font-bold mt-2" style={{ color: 'var(--foreground)' }}>{stats.totalClasses}</p>
                  </div>
                  <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center">
                    <svg className="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                    </svg>
                  </div>
                </div>
              </div>

              <div className="rounded-xl shadow-sm p-6 card" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)', border: '1px solid' }}>
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium" style={{ color: 'var(--foreground)', opacity: 0.7 }}>Payment Status</p>
                    <p className="text-3xl font-bold mt-2" style={{ color: 'var(--foreground)' }}>{stats.paymentStatusPercentage}%</p>
                  </div>
                  <div className="w-12 h-12 bg-indigo-100 rounded-lg flex items-center justify-center">
                    <svg className="w-6 h-6 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
                    </svg>
                  </div>
                </div>
              </div>
            </div>

            {/* My Classes */}
            <div className="rounded-xl shadow-sm p-6 card" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)', border: '1px solid' }}>
              <h2 className="text-lg font-semibold mb-4" style={{ color: 'var(--foreground)' }}>My Classes</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {classes.map((cls) => {
                  const classStudents = getClassStudents(cls._id);
                  return (
                    <div key={cls._id} className="p-4 bg-gradient-to-br from-indigo-50 to-purple-50 rounded-lg border border-indigo-100">
                      <h3 className="font-semibold text-gray-900 mb-2">{cls.name}</h3>
                      <p className="text-sm text-gray-600">{classStudents.length} students</p>
                    </div>
                  );
                })}
                {classes.length === 0 && (
                  <div className="col-span-3 text-center py-8" style={{ color: 'var(--foreground)', opacity: 0.5 }}>
                    No classes yet. Create your first class!
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Classes Tab */}
        {activeTab === 'classes' && (
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <h2 className="text-2xl font-bold" style={{ color: 'var(--foreground)' }}>My Classes</h2>
              <button
                onClick={() => setShowAddClassModal(true)}
                className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition font-medium cursor-pointer"
              >
                + Add Class
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {classes.map((cls) => {
                const classStudents = getClassStudents(cls._id);
                return (
                  <div key={cls._id} className="rounded-xl shadow-sm p-6 card" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)', border: '1px solid' }}>
                    <div className="flex items-start justify-between mb-4">
                      <div>
                        <h3 className="font-semibold text-lg" style={{ color: 'var(--foreground)' }}>{cls.name}</h3>
                        <p className="text-sm mt-1" style={{ color: 'var(--foreground)', opacity: 0.5 }}>
                          Created {new Date(cls.createdAt || '').toLocaleDateString()}
                        </p>
                      </div>
                      <div className="w-10 h-10 bg-indigo-100 rounded-lg flex items-center justify-center">
                        <svg className="w-5 h-5 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                        </svg>
                      </div>
                    </div>

                    <div className="pt-4" style={{ borderTop: '1px solid var(--border-color)' }}>
                      <div className="flex items-center justify-between mb-3">
                        <span className="text-sm" style={{ color: 'var(--foreground)', opacity: 0.7 }}>Students</span>
                        <span className="text-2xl font-bold" style={{ color: 'var(--foreground)' }}>{classStudents.length}</span>
                      </div>
                      
                      {classStudents.length > 0 && (
                        <div className="space-y-1 max-h-32 overflow-y-auto">
                          {classStudents.slice(0, 5).map((student) => (
                            <div key={student._id} className="text-sm flex items-center" style={{ color: 'var(--foreground)', opacity: 0.7 }}>
                              <span className="w-2 h-2 bg-green-400 rounded-full mr-2"></span>
                              {student.name}
                            </div>
                          ))}
                          {classStudents.length > 5 && (
                            <p className="text-xs mt-1" style={{ color: 'var(--foreground)', opacity: 0.5 }}>
                              +{classStudents.length - 5} more
                            </p>
                          )}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Students Tab */}
        {activeTab === 'students' && (
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <h2 className="text-2xl font-bold" style={{ color: 'var(--foreground)' }}>My Students</h2>
              <button
                onClick={() => setShowAddStudentModal(true)}
                className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition font-medium cursor-pointer"
              >
                + Add Student
              </button>
            </div>

            {/* Class Filter */}
            <div className="rounded-lg shadow-sm p-4 card" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)', border: '1px solid' }}>
              <label className="block text-sm font-medium mb-2" style={{ color: 'var(--foreground)' }}>Filter by Class</label>
              <select
                value={selectedClass?._id || ''}
                onChange={(e) => {
                  const cls = classes.find(c => c._id === e.target.value);
                  setSelectedClass(cls || null);
                }}
                className="w-full md:w-64 px-3 py-2 rounded-lg border cursor-pointer"
                style={{ 
                  backgroundColor: 'var(--input-bg)',
                  color: 'var(--foreground)',
                  borderColor: 'var(--input-border)'
                }}
              >
                <option value="">All Classes</option>
                {classes.map((cls) => (
                  <option key={cls._id} value={cls._id}>{cls.name}</option>
                ))}
              </select>
            </div>

            <div className="rounded-xl shadow-sm overflow-hidden card" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)', border: '1px solid' }}>
              <table className="min-w-full divide-y" style={{ borderColor: 'var(--border-color)' }}>
                <thead style={{ backgroundColor: 'var(--card-bg)' }}>
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider" style={{ color: 'var(--foreground)', opacity: 0.7 }}>Student</th>
                    <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider" style={{ color: 'var(--foreground)', opacity: 0.7 }}>Student ID</th>
                    <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider" style={{ color: 'var(--foreground)', opacity: 0.7 }}>Class</th>
                    <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider" style={{ color: 'var(--foreground)', opacity: 0.7 }}>Email</th>
                  </tr>
                </thead>
                <tbody className="divide-y" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)' }}>
                  {(selectedClass 
                    ? students.filter(s => s.classId === selectedClass._id)
                    : students
                  ).map((student) => {
                    const studentClass = classes.find(c => c._id === student.classId);

                    return (
                      <tr key={student._id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="flex items-center">
                            <div className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center mr-3">
                              <span className="text-green-600 font-semibold text-sm">{student.name.charAt(0)}</span>
                            </div>
                            <div className="text-sm font-medium" style={{ color: 'var(--foreground)' }}>{student.name}</div>
                          </div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className="text-sm font-mono" style={{ color: 'var(--foreground)' }}>{student.studentId}</span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          {studentClass && (
                            <span className="px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100 text-blue-800">
                              {studentClass.name}
                            </span>
                          )}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm" style={{ color: 'var(--foreground)', opacity: 0.7 }}>
                          {student.email || '-'}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Attendance Tab */}
        {activeTab === 'attendance' && (
          <div className="space-y-6">
            <h2 className="text-2xl font-bold" style={{ color: 'var(--foreground)' }}>Mark Attendance</h2>

            <div className="rounded-xl shadow-sm p-6 card" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)', border: '1px solid' }}>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                <div>
                  <label className="block text-sm font-medium mb-2" style={{ color: 'var(--foreground)' }}>Select Class *</label>
                  <select
                    value={selectedClass?._id || ''}
                    onChange={(e) => {
                      const cls = classes.find(c => c._id === e.target.value);
                      setSelectedClass(cls || null);
                      setAttendanceRecords({});
                    }}
                    className="w-full px-3 py-2 rounded-lg border cursor-pointer"
                    style={{ 
                      backgroundColor: 'var(--input-bg)',
                      color: 'var(--foreground)',
                      borderColor: 'var(--input-border)'
                    }}
                  >
                    <option value="">Select a class</option>
                    {classes.map((cls) => (
                      <option key={cls._id} value={cls._id}>{cls.name}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2" style={{ color: 'var(--foreground)' }}>Date *</label>
                  <input
                    type="date"
                    value={attendanceDate}
                    onChange={(e) => setAttendanceDate(e.target.value)}
                    className="w-full px-3 py-2 rounded-lg border"
                    style={{ 
                      backgroundColor: 'var(--input-bg)',
                      color: 'var(--foreground)',
                      borderColor: 'var(--input-border)'
                    }}
                  />
                </div>
              </div>

              {selectedClass && (
                <>
                  <div className="space-y-3 mb-6">
                    {getClassStudents(selectedClass._id).map((student) => (
                      <div key={student._id} className="flex items-center justify-between p-4 rounded-lg" style={{ backgroundColor: 'var(--background)' }}>
                        <div className="flex items-center space-x-3">
                          <div className="w-10 h-10 bg-indigo-100 rounded-full flex items-center justify-center">
                            <span className="text-indigo-600 font-semibold">{student.name.charAt(0)}</span>
                          </div>
                          <div>
                            <p className="font-medium" style={{ color: 'var(--foreground)' }}>{student.name}</p>
                            <p className="text-sm" style={{ color: 'var(--foreground)', opacity: 0.5 }}>{student.studentId}</p>
                          </div>
                        </div>

                        <div className="flex space-x-2">
                          <button
                            onClick={() => setAttendanceRecords({ ...attendanceRecords, [student._id]: 'present' })}
                            className={`px-4 py-2 rounded-lg font-medium transition cursor-pointer ${
                              attendanceRecords[student._id] === 'present'
                                ? 'bg-green-600 text-white'
                                : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                            }`}
                          >
                            Present
                          </button>
                          <button
                            onClick={() => setAttendanceRecords({ ...attendanceRecords, [student._id]: 'late' })}
                            className={`px-4 py-2 rounded-lg font-medium transition cursor-pointer ${
                              attendanceRecords[student._id] === 'late'
                                ? 'bg-yellow-600 text-white'
                                : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                            }`}
                          >
                            Late
                          </button>
                          <button
                            onClick={() => setAttendanceRecords({ ...attendanceRecords, [student._id]: 'absent' })}
                            className={`px-4 py-2 rounded-lg font-medium transition cursor-pointer ${
                              attendanceRecords[student._id] === 'absent'
                                ? 'bg-red-600 text-white'
                                : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                            }`}
                          >
                            Absent
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>

                  <button
                    onClick={handleMarkAttendance}
                    className="w-full py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition font-medium cursor-pointer"
                  >
                    Save Attendance
                  </button>
                </>
              )}

              {!selectedClass && (
                <div className="text-center py-12" style={{ color: 'var(--foreground)', opacity: 0.5 }}>
                  Please select a class to mark attendance
                </div>
              )}
            </div>
          </div>
        )}

        {/* Payments Tab */}
        {activeTab === 'payments' && (
          <div className="space-y-6">
            <h2 className="text-2xl font-bold" style={{ color: 'var(--foreground)' }}>Payment Management</h2>
            <div className="rounded-xl shadow-sm p-6 card text-center" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)', border: '1px solid' }}>
              <p style={{ color: 'var(--foreground)', opacity: 0.7 }}>Payment tracking feature coming soon...</p>
            </div>
          </div>
        )}

        {/* View Records Tab */}
        {activeTab === 'records' && (
          <div className="space-y-6">
            <h2 className="text-2xl font-bold" style={{ color: 'var(--foreground)' }}>Attendance Records</h2>
            <div className="rounded-xl shadow-sm p-6 card text-center" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)', border: '1px solid' }}>
              <p style={{ color: 'var(--foreground)', opacity: 0.7 }}>Attendance records view coming soon...</p>
            </div>
          </div>
        )}

        {/* Reports Tab */}
        {activeTab === 'reports' && (
          <div className="space-y-6">
            <h2 className="text-2xl font-bold" style={{ color: 'var(--foreground)' }}>Reports & Analytics</h2>
            <div className="rounded-xl shadow-sm p-6 card text-center" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)', border: '1px solid' }}>
              <p style={{ color: 'var(--foreground)', opacity: 0.7 }}>Reports and analytics coming soon...</p>
            </div>
          </div>
        )}
      </main>

      {/* Add Class Modal */}
      {showAddClassModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="rounded-xl shadow-xl max-w-md w-full p-6 modal-content" style={{ backgroundColor: 'var(--modal-bg)' }}>
            <h3 className="text-lg font-semibold mb-4" style={{ color: 'var(--foreground)' }}>Create New Class</h3>
            
            <div>
              <label className="block text-sm font-medium mb-1" style={{ color: 'var(--foreground)' }}>Class Name *</label>
              <input
                type="text"
                value={newClass.name}
                onChange={(e) => setNewClass({ name: e.target.value })}
                className="w-full px-3 py-2 rounded-lg border"
                style={{ 
                  backgroundColor: 'var(--input-bg)',
                  color: 'var(--foreground)',
                  borderColor: 'var(--input-border)'
                }}
                placeholder="e.g., Mathematics Grade 10"
              />
            </div>

            <div className="flex space-x-3 mt-6">
              <button
                onClick={() => {
                  setShowAddClassModal(false);
                  setNewClass({ name: '' });
                }}
                className="flex-1 px-4 py-2 rounded-lg transition border cursor-pointer"
                style={{ 
                  color: 'var(--foreground)',
                  borderColor: 'var(--border-color)'
                }}
              >
                Cancel
              </button>
              <button
                onClick={handleCreateClass}
                className="flex-1 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition cursor-pointer"
              >
                Create Class
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Add Student Modal */}
      {showAddStudentModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="rounded-xl shadow-xl max-w-md w-full p-6 modal-content" style={{ backgroundColor: 'var(--modal-bg)' }}>
            <h3 className="text-lg font-semibold mb-4" style={{ color: 'var(--foreground)' }}>Add New Student</h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: 'var(--foreground)' }}>Student ID (Auto-generated)</label>
                <input
                  type="text"
                  value={autoGeneratedId}
                  disabled
                  className="w-full px-3 py-2 rounded-lg border bg-gray-100 cursor-not-allowed"
                  style={{ 
                    backgroundColor: 'var(--input-bg)',
                    color: 'var(--foreground)',
                    borderColor: 'var(--input-border)',
                    opacity: 0.7
                  }}
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: 'var(--foreground)' }}>Student Name *</label>
                <input
                  type="text"
                  value={newStudent.name}
                  onChange={(e) => setNewStudent({ ...newStudent, name: e.target.value })}
                  className="w-full px-3 py-2 rounded-lg border"
                  style={{ 
                    backgroundColor: 'var(--input-bg)',
                    color: 'var(--foreground)',
                    borderColor: 'var(--input-border)'
                  }}
                  placeholder="John Doe"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: 'var(--foreground)' }}>Email</label>
                <input
                  type="email"
                  value={newStudent.email}
                  onChange={(e) => setNewStudent({ ...newStudent, email: e.target.value })}
                  className="w-full px-3 py-2 rounded-lg border"
                  style={{ 
                    backgroundColor: 'var(--input-bg)',
                    color: 'var(--foreground)',
                    borderColor: 'var(--input-border)'
                  }}
                  placeholder="student@example.com"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: 'var(--foreground)' }}>Class *</label>
                <select
                  value={newStudent.classId}
                  onChange={(e) => setNewStudent({ ...newStudent, classId: e.target.value })}
                  className="w-full px-3 py-2 rounded-lg border cursor-pointer"
                  style={{ 
                    backgroundColor: 'var(--input-bg)',
                    color: 'var(--foreground)',
                    borderColor: 'var(--input-border)'
                  }}
                >
                  <option value="">Select a class</option>
                  {classes.map((cls) => (
                    <option key={cls._id} value={cls._id}>{cls.name}</option>
                  ))}
                </select>
              </div>
            </div>

            <div className="flex space-x-3 mt-6">
              <button
                onClick={() => {
                  setShowAddStudentModal(false);
                  setNewStudent({ name: '', email: '', classId: '' });
                  setAutoGeneratedId('');
                }}
                className="flex-1 px-4 py-2 rounded-lg transition border cursor-pointer"
                style={{ 
                  color: 'var(--foreground)',
                  borderColor: 'var(--border-color)'
                }}
              >
                Cancel
              </button>
              <button
                onClick={handleCreateStudent}
                className="flex-1 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition cursor-pointer"
              >
                Add Student
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
